---

"COURSE": "CAU_DRALG_2024"
"ASSIGNMENT": "ASSIGNMENT_08"

"ID": "20001234"
"FILES":
    - "**your-path-to-directory**/cau-dralg-2024/assignment_08/binarysearchtree.py" 
"PROBLEMS": 
    - "PROBLEM_01"
    - "PROBLEM_02"
    - "PROBLEM_03"
    - "PROBLEM_04"
    - "PROBLEM_05"
    - "PROBLEM_06A"
    - "PROBLEM_06B"
    - "PROBLEM_06C"
    - "PROBLEM_07A"
    - "PROBLEM_07B"
    - "PROBLEM_08"
    - "PROBLEM_09"
    - "PROBLEM_10"